service: daily-schedule
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ssm:*
          Resource: "arn:aws:ssm:*"
        - Effect: Allow
          Action:
            - ses:*
          Resource: "arn:aws:ses:*"

functions:
  dailySchedule:
    handler: schedule.run
    events:
      - schedule: cron(45 3 ? * * *)
    memorySize: 128
    timeout: 20
  sendReminders:
    handler: reminder.run
    events:
      - schedule: cron(3/5 * ? * * *)
    memorySize: 128
    timeout: 20
